[package]
name = "dungeon-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "~0.8.5"
bevy = { version = "~0.7", features = ["dynamic"] }
serde = "~1.0.137"
ron = "~0.7.0"

